( (c-mode   . ( (c-basic-offset . 2)
                (c-backslash-column . 114)
                (fill-column . 114)))
  (c++-mode . ( (c-basic-offset . 2)
                (c-backslash-column . 114)
                (fill-column . 114))))
