#undef ADDRARG
#undef ALLOC_HEADER_SZ
#undef ASSERTISNOTNULL
#undef BSIZE
#undef BSIZEP
#undef BSTART
#undef BSTARTP
#undef CONS
#undef CONSP
#undef DESCRIBE
#undef DESCRIBEP
#undef DIE
#undef FOR_EACH_BLOCK
#undef FREE_LIST_HEAD
#undef INLINE
#undef IFISNOTNULL
#undef IFISNULL
#undef ISNOTNULL
#undef ISNULL
#undef MIN_ALLOC_SZ
#undef PALLOC_NODE
#undef PFREE_LIST_HEAD
#undef PRHLINE
#undef PRNL
#undef PRINT
#undef PRINTF
#undef PRLINE
#undef PUTCHAR
#undef PVOID
#undef PVOIDC
#undef PVOIDFUN
#undef RCONS
#undef RCONSP
#undef PROOT
#undef SETBSIZE
#undef SETBSIZEP
#undef SIZEARG
#undef UINTPTR
#undef VERBOSEARG
#undef VOIDFUN
#undef palloc_node

#undef RESEUNE_ALLOCATOR_MACROS_HPP
